
# tasks file for roles/nginx
---
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
