---
- name: Pull Docker image
  community.docker.docker_image:
    name: "{{ docker_image }}"
    tag: "{{ docker_tag }}"
    source: pull

- name: Stop existing container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: absent

- name: Start application container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}:{{ docker_tag }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ host_port }}:{{ container_port }}"
